### ISSUE TITLE
missing ability to pass options to lp

### ISSUE THREAD

**Issue by kapouer** [sleep-written/cups-printer#1]
Hi,

this simple library should allow one to pass options to lp - including -o options.
Other than that it's great by its simplicity.

**Comment by sleep-written** [comment]
Hi, thanks for the feedback! I'm glad you find the library attractive due to its simplicity. The idea of passing parameters is indeed great. I'll work on adding that option as soon as possible. Your input is much appreciated.
Best regards.

**Comment by kapouer** [comment]
Well, sorry but at the end the day I chose [another library](https://github.com/NikoHadouken/node-cups).
